### ISSUE TITLE
Fitting everything in the UI

### ISSUE THREAD

**Issue by deweydot** [millers23/Citadels#1]
There seems like there are a lot of cards and information to show on the screen. I'm curious if you want to make the cards collapse to an extent? Perhaps the cards could have a "simplified" view where they show up on the screen and then when you hover over them the card pulls up to its larger form. I don't know up to how many players you will be implementing but if you do go up to 7 it seems necessary to maybe even have multiple windows of some sort?

**Comment by millers23** [comment]
I re-made the UI to better suit and visualize the cards that need to be shown. There should also be an option to view someone else's data to see what they have built and what their score is
