### ISSUE TITLE
null object reference

### ISSUE THREAD

**Issue by madison2023** [millers23/Citadels#2]
I’m not sure if this will actually help you but I noticed that your team changed line 637 in GameMainActivity. In the original framework that line is:
 return launchGame(finalConfig, null); 
In your code it was:
return launchGame(finalConfig, getGameState());
I think this might be what was causing one of the errors.
When I changed the code back to the original line, it still crashed, but it printed a different error instead.

**Comment by millers23** [comment]
Thanks, I'll look into it
